### ISSUE TITLE
Still Unable to execute the script 

### ISSUE THREAD

**Issue by karimmd** [nanotechz9l/Source-code-analyzer#6]
I have tried with both Ruby version 1.9.3 and 2.0.0, even I have installed both gem package named "rainbow" and "english".But when I want to execute the script,getting the following error
C:\Ruby200\bin>ruby.exe vulnxpose.rb test.c
vulnxpose.rb:27:in `v': undefined method`foreground' for #String:0xfd2258 (NoMethodError)
        from vulnxpose.rb:47:in `<main>'

**Comment by nanotechz9l** [comment]
The developer changed the rainbow gem file structure. Instead of require 'rainbow', its something like require 'rainbow/ext/string' or something.
